# Generated by Django 3.2.7 on 2021-09-25 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.group'),
        ),
    ]
