# Generated by Django 3.2.7 on 2021-09-26 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='region',
            name='orphanages',
            field=models.ManyToManyField(blank=True, to='main.Orphanage'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.region'),
        ),
        migrations.AddField(
            model_name='child',
            name='orphanage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.orphanage'),
        ),
        migrations.AddField(
            model_name='child',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
