# Generated by Django 3.2.7 on 2021-09-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='first_name',
            field=models.CharField(default='Ivanov', max_length=50),
        ),
        migrations.AlterField(
            model_name='basicuser',
            name='second_name',
            field=models.CharField(default='Ivan', max_length=50),
        ),
    ]
